version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      AWS_XRAY_DAEMON_ADDRESS: "daemon:2000"
      AWS_LOG_GROUP: "/docker/my-docker-group"
  daemon:
    image: "public.ecr.aws/xray/aws-xray-daemon:latest"
    environment:
      AWS_REGION: "us-west-2"
    command: "-l debug -t 0.0.0.0:2000 -b 0.0.0.0:2000"
    ports:
      - "2000:2000/tcp"
      - "2000:2000/udp"
